"""Create tables without category

Revision ID: 0b3b7831134e
Revises: 
Create Date: 2025-12-11 16:02:28.112049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b3b7831134e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('pwd', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('department', sa.String(length=25), nullable=False),
    sa.Column('position', sa.String(length=25), nullable=False),
    sa.Column('phone_number', sa.String(length=11), nullable=False),
    sa.Column('e_mail', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('e_mail')
    )
    op.create_table('machine',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('creator', sa.String(length=25), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maker',
    sa.Column('id', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('id', sa.String(length=6), nullable=False),
    sa.Column('maker_id', sa.String(length=4), nullable=False),
    sa.Column('major', sa.String(length=50), nullable=False),
    sa.Column('minor', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('solo_price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['maker_id'], ['maker.id'], ),
    sa.PrimaryKeyConstraint('id', 'maker_id')
    )
    op.create_table('certification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resources_id', sa.String(length=6), nullable=False),
    sa.Column('maker_id', sa.String(length=4), nullable=False),
    sa.Column('ul', sa.Boolean(), nullable=False),
    sa.Column('ce', sa.Boolean(), nullable=False),
    sa.Column('kc', sa.Boolean(), nullable=False),
    sa.Column('etc', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['resources_id', 'maker_id'], ['resources.id', 'resources.maker_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machine_resources',
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('maker_id', sa.String(length=4), nullable=False),
    sa.Column('resources_id', sa.String(length=6), nullable=False),
    sa.Column('solo_price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['maker_id', 'resources_id'], ['resources.maker_id', 'resources.id'], ),
    sa.PrimaryKeyConstraint('machine_id', 'maker_id', 'resources_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('machine_resources')
    op.drop_table('certification')
    op.drop_table('resources')
    op.drop_table('maker')
    op.drop_table('machine')
    op.drop_table('account')
    # ### end Alembic commands ###
