from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '191408b505a4'
down_revision: Union[str, None] = '796aa1cd56b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('client', sa.String(length=50), nullable=True),
    sa.Column('creator', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detailed',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('general_id', sa.UUID(), nullable=False),
    sa.Column('creator', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['general_id'], ['general.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_compare',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('general_id', sa.UUID(), nullable=False),
    sa.Column('creator', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['general_id'], ['general.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('general_id', sa.UUID(), nullable=False),
    sa.Column('creator', sa.String(length=25), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('client', sa.String(length=50), nullable=True),
    sa.Column('pic_name', sa.String(length=50), nullable=True),
    sa.Column('pic_position', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('description_1', sa.Text(), nullable=True),
    sa.Column('description_2', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['general_id'], ['general.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detailed_resources',
    sa.Column('detailed_id', sa.UUID(), nullable=False),
    sa.Column('major', sa.String(length=30), nullable=False),
    sa.Column('minor', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('solo_price', sa.Integer(), nullable=False),
    sa.Column('compare', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['detailed_id'], ['detailed.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('detailed_id', 'major', 'minor')
    )
    op.create_table('price_compare_machine',
    sa.Column('price_compare_id', sa.UUID(), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['price_compare_id'], ['price_compare.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('price_compare_id', 'machine_id')
    )
    op.create_table('price_compare_resources',
    sa.Column('price_compare_id', sa.UUID(), nullable=False),
    sa.Column('major', sa.String(length=30), nullable=False),
    sa.Column('minor', sa.String(length=50), nullable=False),
    sa.Column('cost_solo_price', sa.Integer(), nullable=False),
    sa.Column('cost_unit', sa.String(length=10), nullable=False),
    sa.Column('cost_compare', sa.Integer(), nullable=False),
    sa.Column('quotation_solo_price', sa.Integer(), nullable=False),
    sa.Column('quotation_unit', sa.String(length=10), nullable=False),
    sa.Column('quotation_compare', sa.Integer(), nullable=False),
    sa.Column('upper', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['price_compare_id'], ['price_compare.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('price_compare_id', 'major', 'minor')
    )
    op.create_table('quotation_resources',
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('spac', sa.String(length=50), nullable=True),
    sa.Column('compare', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('solo_price', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quotation_id', 'name')
    )
    
    # -----------------------------------------------------------
    # 🚀 [수정된 로직] resources 테이블 display_order 컬럼 추가
    # NOT NULL 오류를 방지하기 위해 3단계로 안전하게 처리
    # -----------------------------------------------------------
    
    # 1. 컬럼을 nullable=True 상태로 먼저 추가
    op.add_column('resources', sa.Column('display_order', sa.Integer(), nullable=True)) 
    
    # 2. 기존 데이터에 기본값 (0) 설정
    # 기존 레코드의 NULL 값을 0으로 채워 NOT NULL 제약 조건 활성화에 대비
    op.execute("UPDATE resources SET display_order = 0 WHERE display_order IS NULL")
    
    # 3. 컬럼의 nullable 제약 조건을 False로 변경
    op.alter_column(
        'resources', 
        'display_order', 
        existing_type=sa.Integer(), 
        nullable=False,
        existing_nullable=True
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'display_order')
    op.drop_table('quotation_resources')
    op.drop_table('price_compare_resources')
    op.drop_table('price_compare_machine')
    op.drop_table('detailed_resources')
    op.drop_table('quotation')
    op.drop_table('price_compare')
    op.drop_table('detailed')
    op.drop_table('general')
    # ### end Alembic commands ###