"""Add machine and machine_resources tables

Revision ID: 1a69a14ec676
Revises: 
Create Date: 2025-12-09 02:26:47.012332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a69a14ec676'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machine_resources',
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('maker_id', sa.String(length=4), nullable=False),
    sa.Column('resources_id', sa.String(length=6), nullable=False),
    sa.Column('solo_price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['maker_id', 'resources_id'], ['resources.maker_id', 'resources.id'], ),
    sa.PrimaryKeyConstraint('machine_id', 'maker_id', 'resources_id')
    )
    op.drop_index('idx_category_major', table_name='category')
    op.drop_constraint('uk_category_major_minor', 'category', type_='unique')
    op.drop_index('idx_cert_resource', table_name='certification')
    op.drop_constraint('uk_cert_resource', 'certification', type_='unique')
    op.drop_index('idx_maker_name', table_name='maker')
    op.drop_index('idx_resources_category', table_name='resources')
    op.drop_index('idx_resources_name', table_name='resources')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_resources_name', 'resources', ['name'], unique=False)
    op.create_index('idx_resources_category', 'resources', ['category_id'], unique=False)
    op.create_index('idx_maker_name', 'maker', ['name'], unique=False)
    op.create_unique_constraint('uk_cert_resource', 'certification', ['resources_id', 'maker_id'])
    op.create_index('idx_cert_resource', 'certification', ['resources_id', 'maker_id'], unique=False)
    op.create_unique_constraint('uk_category_major_minor', 'category', ['major', 'minor'])
    op.create_index('idx_category_major', 'category', ['major'], unique=False)
    op.drop_table('machine_resources')
    op.drop_table('machine')
    # ### end Alembic commands ###
