"""Add manufacturer, client, creator, price, description to machine

Revision ID: 26232116a2b1
Revises: 0b3b7831134e
Create Date: 2025-12-11 20:48:07.562713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26232116a2b1'
down_revision: Union[str, None] = '0b3b7831134e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine', sa.Column('manufacturer', sa.String(length=50), nullable=True))
    op.add_column('machine', sa.Column('client', sa.String(length=50), nullable=True))
    op.add_column('machine', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machine', 'price')
    op.drop_column('machine', 'client')
    op.drop_column('machine', 'manufacturer')
    # ### end Alembic commands ###
