"""add_price_compare_resources_machine_id

Revision ID: 2dcc26f2fa70
Revises: 191408b505a4
Create Date: 2025-12-16 18:05:41.279135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dcc26f2fa70'
down_revision: Union[str, None] = '191408b505a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_compare_resources', sa.Column('machine_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'price_compare_resources', 'machine', ['machine_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'price_compare_resources', type_='foreignkey')
    op.drop_column('price_compare_resources', 'machine_id')
    # ### end Alembic commands ###
