"""add_order_index_column

Revision ID: 796aa1cd56b2
Revises: 8acee6127d88
Create Date: 2025-12-15 07:35:32.494121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '796aa1cd56b2'
down_revision: Union[str, None] = '8acee6127d88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_machine_resources_machine_id_order_index', 'machine_resources', type_='unique')
    op.drop_index('ix_resources_display_order', table_name='resources')
    op.drop_column('resources', 'display_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_resources_display_order', 'resources', ['display_order'], unique=False)
    op.create_unique_constraint('uq_machine_resources_machine_id_order_index', 'machine_resources', ['machine_id', 'order_index'])
    # ### end Alembic commands ###
