"""add_manufacturer_to_general

Revision ID: ee387dbc2598
Revises:
Create Date: 2025-12-26 10:14:40.946246

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee387dbc2598"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "general",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("client", sa.String(length=50), nullable=True),
        sa.Column("creator", sa.String(length=25), nullable=False),
        sa.Column("manufacturer", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "machine",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("manufacturer", sa.String(length=50), nullable=True),
        sa.Column("client", sa.String(length=50), nullable=True),
        sa.Column("creator", sa.String(length=25), nullable=False),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "maker",
        sa.Column("id", sa.String(length=4), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "permission",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("resource", sa.String(length=50), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("resource", "action", name="uq_permission_resource_action"),
    )
    op.create_table(
        "role",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "account",
        sa.Column("id", sa.String(length=25), nullable=False),
        sa.Column("pwd", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=10), nullable=False),
        sa.Column("department", sa.String(length=25), nullable=False),
        sa.Column("position", sa.String(length=25), nullable=False),
        sa.Column("phone_number", sa.String(length=11), nullable=False),
        sa.Column("e_mail", sa.String(length=255), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("e_mail"),
    )
    op.create_table(
        "folder",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("general_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["general_id"],
            ["general.id"],
            name="fk_detailed_general_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "resources",
        sa.Column("id", sa.String(length=6), nullable=False),
        sa.Column("maker_id", sa.String(length=4), nullable=False),
        sa.Column("major", sa.String(length=50), nullable=False),
        sa.Column("minor", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("unit", sa.String(length=10), nullable=False),
        sa.Column("solo_price", sa.Integer(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["maker_id"],
            ["maker.id"],
        ),
        sa.PrimaryKeyConstraint("id", "maker_id"),
    )
    op.create_table(
        "role_permission",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["permission.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "certification",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("resources_id", sa.String(length=6), nullable=False),
        sa.Column("maker_id", sa.String(length=4), nullable=False),
        sa.Column("ul", sa.Boolean(), nullable=False),
        sa.Column("ce", sa.Boolean(), nullable=False),
        sa.Column("kc", sa.Boolean(), nullable=False),
        sa.Column("etc", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["resources_id", "maker_id"],
            ["resources.id", "resources.maker_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "header",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("folder_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("creator", sa.String(length=25), nullable=False),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("client", sa.String(length=50), nullable=True),
        sa.Column("manufacturer", sa.String(length=50), nullable=True),
        sa.Column("pic_name", sa.String(length=50), nullable=True),
        sa.Column("pic_position", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("description_1", sa.Text(), nullable=True),
        sa.Column("description_2", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["folder_id"], ["folder.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "machine_resources",
        sa.Column("machine_id", sa.UUID(), nullable=False),
        sa.Column("resources_id", sa.String(length=6), nullable=False),
        sa.Column("maker_id", sa.String(length=4), nullable=False),
        sa.Column("solo_price", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("display_major", sa.String(length=50), nullable=True),
        sa.Column("display_minor", sa.String(length=50), nullable=True),
        sa.Column("display_model_name", sa.String(length=100), nullable=True),
        sa.Column("display_maker_name", sa.String(length=100), nullable=True),
        sa.Column("display_unit", sa.String(length=10), nullable=True),
        sa.ForeignKeyConstraint(["machine_id"], ["machine.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["resources_id", "maker_id"],
            ["resources.id", "resources.maker_id"],
        ),
        sa.PrimaryKeyConstraint("machine_id", "resources_id", "maker_id"),
    )
    op.create_table(
        "price_compare",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("folder_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("creator", sa.String(length=25), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["folder_id"], ["folder.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "detailed",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("folder_id", sa.UUID(), nullable=False),
        sa.Column("price_compare_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("creator", sa.String(length=25), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["folder_id"],
            ["folder.id"],
            name="fk_detailed_folder_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["price_compare_id"],
            ["price_compare.id"],
            name="fk_detailed_price_compare_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "header_resources",
        sa.Column("header_id", sa.UUID(), nullable=False),
        sa.Column("machine", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("spac", sa.String(length=50), nullable=True),
        sa.Column("compare", sa.Integer(), nullable=False),
        sa.Column("unit", sa.String(length=10), nullable=False),
        sa.Column("solo_price", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["header_id"], ["header.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("header_id", "machine", "name"),
    )
    op.create_table(
        "price_compare_machine",
        sa.Column("price_compare_id", sa.UUID(), nullable=False),
        sa.Column("machine_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["machine_id"], ["machine.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["machine_id"], ["machine.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["price_compare_id"], ["price_compare.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["price_compare_id"], ["price_compare.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("price_compare_id", "machine_id"),
    )
    op.create_table(
        "price_compare_resources",
        sa.Column("price_compare_id", sa.UUID(), nullable=False),
        sa.Column("machine_id", sa.UUID(), nullable=False),
        sa.Column("machine_name", sa.String(length=100), nullable=False),
        sa.Column("major", sa.String(length=30), nullable=False),
        sa.Column("minor", sa.String(length=50), nullable=False),
        sa.Column("cost_solo_price", sa.Integer(), nullable=False),
        sa.Column("cost_unit", sa.String(length=10), nullable=False),
        sa.Column("cost_compare", sa.Integer(), nullable=False),
        sa.Column("quotation_solo_price", sa.Integer(), nullable=False),
        sa.Column("quotation_unit", sa.String(length=10), nullable=False),
        sa.Column("quotation_compare", sa.Integer(), nullable=False),
        sa.Column("upper", sa.Float(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["price_compare_id"], ["price_compare.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint(
            "price_compare_id", "machine_id", "machine_name", "major", "minor"
        ),
    )
    op.create_table(
        "detailed_resources",
        sa.Column("detailed_id", sa.UUID(), nullable=False),
        sa.Column(
            "machine_name",
            sa.String(length=100),
            nullable=False,
            comment="snapshot: not a FK",
        ),
        sa.Column("major", sa.String(length=30), nullable=False),
        sa.Column("minor", sa.String(length=50), nullable=False),
        sa.Column("unit", sa.String(length=10), nullable=False),
        sa.Column("solo_price", sa.Integer(), nullable=False),
        sa.Column("compare", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["detailed_id"], ["detailed.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("detailed_id", "machine_name", "major", "minor"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("detailed_resources")
    op.drop_table("price_compare_resources")
    op.drop_table("price_compare_machine")
    op.drop_table("header_resources")
    op.drop_table("detailed")
    op.drop_table("price_compare")
    op.drop_table("machine_resources")
    op.drop_table("header")
    op.drop_table("certification")
    op.drop_table("role_permission")
    op.drop_table("resources")
    op.drop_table("folder")
    op.drop_table("account")
    op.drop_table("role")
    op.drop_table("permission")
    op.drop_table("maker")
    op.drop_table("machine")
    op.drop_table("general")
    # ### end Alembic commands ###
